services:
  - type: web
    name: prepvista-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r backend/requirements.txt
    startCommand: "gunicorn app:app"
    pythonVersion: 3.10.12
